### ISSUE TITLE
Update required Patch 4.5

### ISSUE THREAD

**Issue by Program-arg** [Necromancerx/lor-wallpaper-downloader#1]
Hello, could you update it? , thank you very much!

**Comment by pauloapi** [comment]
I encountered an issue with the new patch where the compressed wallpaper file now exceeds the maximum file size limit of 2GB on GitHub. As a solution, I am in the process of transferring the release to an alternative provider or considering hosting it on my own website. I will provide you with an update later today.

**Comment by pauloapi** [comment]
You can now access the latest release here https://github.com/Necromancerx/lor-wallpaper-downloader/releases/tag/2023-05-26
I uploaded the file on S3 for now while I'm developing the new website.
